로또 생성기 step1 구현
my-js-study/js-lotto pull request #1
Opened 2022-04-09 20:17 UTC by parksil0

안녕하세요!

이번 과제에서는 view와 controller를 분리해 보았습니다.

부족하지만, 잘 부탁드립니다..!

고맙습니다 😄

2022-04-13 15:00 UTC, yujo11 requested changes
안녕하세요 박실님~ 

전체적으로 얘기 나누고 싶은 부분들이 있어 추가로 코멘트를 남깁니다.

1. Controller와 View의 역할
- View와 Controller가 각각 어떤 역할을 하기 위해 구분하신건지 궁금합니다. 

2. class의 사용
- 굳이 class를 사용할 필요가 없어 보이는데 전체적인 코드가 class로 되어 있네용
- class를 사용하신 이유를 알 수 있을까요?

3. Event 사용
- custom event를 사용하시는 이유가 있을까용?

---

지난 미션처럼 이번에도 코드가 깔끔해서 보기 좋았습니다! 구현하느라 고생 많으셨습니다! 👍 👍 👍

2022-04-13 15:00 UTC, yujo11 commented on cypress/integration/lotto.spec.js
> +describe('step1 필수 요구사항', () => {
현재 크게 보면 로또를 구입하는 부분과 로또 구입 이후 부분으로 테스트를 나눠볼 수 있을거 같은데요. `context`를 통해 문맥을 분리해주시면 테스트 코드 보기가 더 편할거 같네용

2022-04-13 15:00 UTC, yujo11 commented on src/index.js
> +});
현재 class의 instance들이 딱 한번만 생성되고 있는데 굳이 class로 코드를 작성할 필요가 있을까요?

2022-04-13 15:00 UTC, yujo11 commented on src/utils/dom.js
> +}
셀렉터 함수에 error 처리가 추가 되었군요! 👍 👍 👍

2022-04-13 15:00 UTC, yujo11 commented on src/views/PurchasedLottosView.js
> +}
굳이 class일 필요가 있는지 모르겠네요

2022-04-13 15:00 UTC, yujo11 commented on src/views/InputPriceFormView.js
> +    this.inputPrice = $('#input-price');
input을 DOM에서 파싱해오지 않고 submit event 객체에서 값을 가져오면 더 좋을거 같네용

2022-04-13 15:00 UTC, yujo11 commented on src/views/InputPriceFormView.js
> +  }
이 이벤트가 필요할까요?

2022-04-13 15:00 UTC, yujo11 commented on src/Controller.js
> +    );
커스텀 이벤트를 사용하신건가요? 커스텀 이벤트를 사용하시는 이유가 있을까요?

2022-04-15 15:19 UTC, Tanney-102 requested changes
실님 안녕하세요~~
리뷰 늦어서 정말 죄송합니다ㅠㅠㅠㅠㅠ
코멘트 확인부탁드립니다 ㅎㅎ

2022-04-15 15:19 UTC, Tanney-102 commented on .eslintrc.js
> +    'eslint-config-prettier',
'prettier'만 넣으셔도 될겁니다

2022-04-15 15:19 UTC, Tanney-102 commented on cypress/integration/lotto.spec.js
> +      expect(input[0].validationMessage).to.eq('Please fill out this field.');
validationMessage는 환경에 따라 localize되어서 나온다고 알고 있습니다!
이 테스트는 환경에 따라 실패할 수도 있을 것 같아요~

2022-04-15 15:19 UTC, Tanney-102 commented on src/Controller.js
> +    this.render();
controller인만큼 render 보다는 정확히 어떤 일을하는지 명시적으로 나타내 주는 게 좋지 않을까요?
하나의 컨트롤러가 여러 뷰를 관리하는 경우가 대부분일텐데 render라는 이름으로는 어떤 뷰에 어떤 일이 일어나는지 예측하기 어려울 것 같습니다

2022-04-15 15:19 UTC, Tanney-102 commented on src/Controller.js
> +      this.inputLottoNumsView.hide();
깔끔허니 좋네요 👍

2022-04-15 15:19 UTC, Tanney-102 commented on src/css/ui/index.css
> +/* 20220410 Seal: 하단 부로 새로 추가 */
꼭 필요한 주석일까요?

2022-04-15 15:19 UTC, Tanney-102 commented on src/utils/dom.js
> +}
👍

2022-04-15 15:19 UTC, Tanney-102 commented on src/utils/getRandomLottoNumbers.js
> +  return array.map((_) => generateLotto());
```suggestion
  return Array.from({ length: number }, (_) => generateLotto());
```

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/InputPriceFormView.js
> +      e.preventDefault();
무엇을 막기 위한 로직인가요?

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/InputPriceFormView.js
> +    }
```suggestion
    if (value >= MIN_INPUT_PRICE || value % MIN_INPUT_PRICE) {
      e.preventDefault();
      alert(ERROR_MESSAGE.NOT_TYPE_UNIT_OF_THOUSAND);
      this.inputPrice.value = '';
      return;
    }

    const numberOfLottos = value / MIN_INPUT_PRICE;       
    this.emit(CUSTOM_EVENT_NAME.INPUT_PRICE_FORM_SUBMIT, {
      value: numberOfLottos,
    })
```

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/InputPriceFormView.js
> +  }
this.element가 form인데 submit 이벤트를 잡아서 처리하면 어떨까요?
enter입력에 대한 대응도 할 수 있고 event.target을 통해 input 엘리먼트를 가져올 수 있습니다. (즉 this.inputPrice 도 필요 없어집니다.)

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/PurchasedLottosView.js
> +    super($('#purchased-lottos'));
this.element는 잘 사용하지 않는 것 같은데 매번 초기화 해주는 이유가 있을까요?

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/PurchasedLottosView.js
> +    this.lottoIcons.classList.toggle('flex-col');
toggle보다는 add나 remove를 사용하면 어떨까요?
이 코드만으로는 flex-col이 추가될지 제거될지 예상하기 어렵습니다.
이 로직만 있다면 모를까 다른 로직들과 정확히 싱크될지 보장하기 어려울 것 같아요

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/PurchasedLottosView.js
> +    lottoDetails.forEach((el) => setDisplay(el, 'inline'));
만약 lottoDetails의 display가 block이나 inline-block으로 바뀌면 여기 코드도 수정되어야겠군요~
운이좋아 기억하면 다행이지만 아~주 나중에 수정되거나 혹은 다른 사람에 의해 수정될 경우에는 문제가 될 수 있습니다.
이 문제를 어떻게 해결할 수 있을지 고민해보시면 좋겠습니다!

2022-04-15 15:19 UTC, Tanney-102 commented on src/views/View.js
> +    this.element.addEventListener(eventName, handler);
아 this.element가 여기서 쓰이는군요 ㅋㅋ
이해했습니다

2022-04-15 15:19 UTC, Tanney-102 commented on index.html
> +              <button type="submit" id="input-price-btn" class="btn btn-cyan">
button의 type은 default가 submit인데 알고 의도하신걸까요?
IE는 default type이 button이긴해서 의도적으로 적어주신 건지 궁금합니다!

2022-04-15 15:20 UTC, Tanney-102 commented on src/Controller.js
> +    );
MVC 아키텍처에서 view의 이벤트를 controller에 전달하기 위한 방법으로 많이 사용하는 걸로 알고 있습니다~

2022-04-16 02:24 UTC, parksil0 commented on src/index.js
> +});
컨트롤러의 인자로 받은 뷰 들은 각각 `View`라는 조상 클래스를 상속받은 클래스들이에요. 각 뷰에서 공통적으로 사용되는 메서드들이 있는데, 이왕이면 상위 클래스를 하나 만들어서 상속을 시키면 좋겠다는 생각에 클래스로 코드를 작성했습니다.

2022-04-16 02:26 UTC, parksil0 commented on src/views/PurchasedLottosView.js
> +}
나중에 코드가 길어질 때 확실히 구분할 수 있도록 한 파일 안에 템플릿이라는 클래스를 생성했는데, 오히려 과하다고 생각할 수도 있겠네요.

2022-04-16 03:12 UTC, parksil0 commented on src/Controller.js
> +    );
넵 컨트롤러는 subscribe라는 메서드를 통해 custom event를 생성하고요, 컨트롤러에서 관리되는 뷰 들은 custom event를 emit(`eventTarget.dispatchEvent()`)하는 형태로 만들어봤습니다.

사용하는 이유는 태은님이 말씀하신 대로, 저도 js로 MVC패턴을 구현할 때 몇몇 곳에서 사용되는 걸 보고 사용을 한 것도 맞고요,
커스텀 이벤트를 사용했을 때 보다 명확하게 구분할 수 있어 사용을 했습니다. 컨트롤러 내에 관리되는 뷰에서 어떠한 이벤트가 발생했을 때 크게 두가지로 나눠서 이벤트를 실행합니다.
1. 해당 뷰 내에서 이벤트를 처리해도 되는 때 -> 일반적인 이벤트를 선언 및 실행
2. 컨트롤러에게 알려야 할 때 -> 컨트롤러에서 생성한 커스텀 이벤트를 emit

위처럼 구분 기준을 가지고 이벤트를 만들면 보다 가독성도 높아지고, 역할도 분명해져서 저는 개인적으로 컨트롤러와 뷰를 만들 때에는 자주 사용하는 편입니다 ㅎㅎ

2022-04-16 03:23 UTC, parksil0 commented on src/views/InputPriceFormView.js
> +      e.preventDefault();
submit이 실행되지 않기위한 로직이에요. 유효성 검증에서 실패했을 때 submit이 되지 않고, alert을 통해 에러메세지를 뱉도록 설계한 코드입니다.

2022-04-16 03:25 UTC, parksil0 commented on index.html
> +              <button type="submit" id="input-price-btn" class="btn btn-cyan">
엇... 아뇨 IE에서 default로 button인지는 몰랐어요 ㅋㅋ
생략해도 되지만, 명시적으로 알리는게 좋지 않을까 해서 넣긴 했는데, 굳이? 라는 반응이면 빼볼게요

2022-04-16 18:00 UTC, parksil0 commented
> 안녕하세요 박실님~
> 
> 전체적으로 얘기 나누고 싶은 부분들이 있어 추가로 코멘트를 남깁니다.
> 
> 1. Controller와 View의 역할
> 
> * View와 Controller가 각각 어떤 역할을 하기 위해 구분하신건지 궁금합니다.
> 
> 2. class의 사용
> 
> * 굳이 class를 사용할 필요가 없어 보이는데 전체적인 코드가 class로 되어 있네용
> * class를 사용하신 이유를 알 수 있을까요?
> 
> 3. Event 사용
> 
> * custom event를 사용하시는 이유가 있을까용?
> 
> 지난 미션처럼 이번에도 코드가 깔끔해서 보기 좋았습니다! 구현하느라 고생 많으셨습니다! 👍 👍 👍

안녕하세요 윤호님! 리뷰 감사합니다.

질문 주신 내용에 대한 답변입니다!

1. Controller, View의 역할

* Controller는 로또 생성에 관련된 각각의 View를 관리하는 역할입니다. 각 View의 상호작용을 돕고자 만들었어요. Controller에 할당된 각각 View 내에서만 작동하는 이벤트는 해당 View에서 이벤트를 관리하지만, 해당 View의 이벤트로 인하여 다른 View에 화면을 제어하고 싶을 때 Controller를 통해 요청을 보내도록 설계했어요!

2. class의 사용

* ~~View.js 파일들은 조상 클래스인 [View.js](https://github.com/my-js-study/js-lotto/blob/935eb5cfdc0b6625c2d17d8fd02ea7aebb80ee04/src/views/View.js)라는 클래스에서 상속을 받아요. 각각의 View 파일들은 공통적으로 사용되는 메서드가 있습니다. 중복되는 코드를 줄이고, 그로인해 일관성이 높아지면서, 동시에 가독성을 높이는 방법이 클래스를 사용하는 것이라고 생각했어요!
* 다만 Controller는 클래스 사용의 의미는 없지만, 일반적인 자바스크립트에서 MVC(로또에는 Modal을 다루진 않지만..)를 사용할 때 보통은 클래스를 사용해서 Controller에도 클래스를 사용했습니다!

3. Controller에서의 custom event

* 1번의 연장선인데, 특정 View가 다른 View의 화면을 조작하고 싶을 때 Controller를 통해서 요청을 보냅니다. Controller는 Custom Event를 통해 다른 View의 화면을 조작하고 싶은 View에게 위임하고(보통 위임하는 메서드의 네이밍이 subscribe더라고요), 할당 받은 View가 이벤트를 실행할 때 Controller의 메서드가 실행하면서 동시에 다른 View의 화면을 조작하는 흐름입니다!

2022-04-16 18:13 UTC, parksil0 commented
안녕하세요 윤호님, 태은님!

리뷰 주신 내용 감사합니다.
리뷰 반영하여 다시 코드를 작성해 봤어요.

* test 파일 내의 context() 추가하여 문맥 별 나누기 : [6ba6ad6](https://github.com/my-js-study/js-lotto/pull/1/commits/6ba6ad62f0de92771b1e1ca7ceffc0b14e0f539f)
* 하나의 파일 내에 클래스가 두 개인 경우 리팩토링(Template 클래스 제거) : [b6546ca](https://github.com/my-js-study/js-lotto/pull/1/commits/b6546ca0f8a42ceb9e15a7f24d3cbfa3e0911fd5)
* 버튼 클릭 이벤트 대신 form의 submit이벤트 설정 : [8c88fd8](https://github.com/my-js-study/js-lotto/pull/1/commits/8c88fd8bbfec551fd5f4a9e2bbbcf73872ac976a)
* input의 유효성처리 에러메세지 설정 : [78d0ee4](https://github.com/my-js-study/js-lotto/pull/1/commits/78d0ee4bd4e4f7f1508b1884003d2ca1ba0ccfe4)
* element.classList.toggle()과 같이 파악하기 어려운 코드 개선 : [70dead7](https://github.com/my-js-study/js-lotto/pull/1/commits/70dead7165933af862dbcb6e456da3ace18d1c40)
* View 내에서 직접 style을 설정하지 않고, 클래스 설정 : [935eb5c](https://github.com/my-js-study/js-lotto/pull/1/commits/935eb5cfdc0b6625c2d17d8fd02ea7aebb80ee04)
* 그 외의 minor한 변경
   * 불필요한 코드 제거 : [da93583](https://github.com/my-js-study/js-lotto/pull/1/commits/da935838088d2e2d059f436a16276910b5a5b9b0), [3f25d8d](https://github.com/my-js-study/js-lotto/pull/1/commits/3f25d8dfc361a84d441b340e206c9ef3e6a21872), [03394fb](https://github.com/my-js-study/js-lotto/pull/1/commits/03394fb6412be91297b6fa4831c8ffd15eada9a1)
   * 애매한 함수 이름 변경 : [589dcf7](https://github.com/my-js-study/js-lotto/pull/1/commits/589dcf71a698324bf3ae95b0026899b42f731eb5)
   * 불필요한 할당 제거 : [77714db](https://github.com/my-js-study/js-lotto/pull/1/commits/77714dbbd392e3a0c3add014e0832e8cfa1cd957)

혹시라도 제가 리뷰의 요지를 제대로 이해 못한 부분이 있다면, 리뷰 주시면 감사하겠습니다!

2022-04-17 09:14 UTC, Tanney-102 commented on index.html
> +              <button type="submit" id="input-price-btn" class="btn btn-cyan">
앗 아뇨 굳이까지는 아니구요! 일관된 컨벤션으로 유지만 한다면 명시적으로 나타내는 것도 좋다고 생각합니다 ㅎㅎ
실제로 type을 안 써버릇 하다가 form 안에서 예상치 못한 submit 이벤트가 발생하는 경우도 있고 사실 IE의 케이스처럼 submit이 default인지 여부는 브라우저에게 의존하게 되는 영역이라 직접 적어주는 편이 좋아보이기도 하네요!

2022-04-20 13:06 UTC, yujo11 approved these changes
이번 스텝에서 추가로 코멘트 드릴만한 부분은 못 찾겠네요!

고생 많으셨습니다! 👍 👍 👍

2022-04-21 10:52 UTC, Tanney-102 approved these changes
늦게 확인해서 정말정말 죄송합니다ㅠㅠㅠ
간단히 코멘트 드렸어요!
우선 srcElement에 대한 부분만 수정하시고 머지하시면 좋을 것 같습니다!
아니면 우선 머지하고 다음 스텝에서 수정하셔도 좋겠네요!

2022-04-21 10:52 UTC, Tanney-102 commented on src/views/InputPriceFormView.js
> +    const { value } = e.srcElement['input-price'];
https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement

srcElement는 deprecated 된 스펙입니다!

2022-04-21 10:52 UTC, Tanney-102 commented on src/views/InputPriceFormView.js
> +    const { value } = e.srcElement['input-price'];
```js
const $input =  e.target.elements['input-price']
const { value } = $input
```

2022-04-21 10:52 UTC, Tanney-102 commented on src/views/PurchasedLottosView.js
> +      });
class를 사용하는 방식은 아주 굳입니다~
다만 `lotto-details-display-show`까지 매번 넣어주고 빼주고 해야할까 싶어요!
기본적으로 lottoDetails 엘리먼트들이 display: inline 속성을 가지고 있고
필요시에만 display-none 클래스를 추가해 display속성을 오버라이딩 해주는 방식은 어떨까 싶네요~
요 부분은 개인적인 의견이니 고민해보시고 반영할지 결정하시면 되겠습니다!

2022-04-22 07:05 UTC, merged